### ISSUE TITLE
grammarly exited with status code 1

### ISSUE THREAD

**Issue by reagle** [sublimelsp/LSP-Grammarly#13]
Once installed I immediately get this pop-up.

![SCR-20220922-dzy](https://user-images.githubusercontent.com/596814/191770085-c4391962-4e8c-461d-bb36-074735bb3ce2.png)

**Comment by pnhuy** [comment]
Dupplicated to this: https://github.com/sublimelsp/LSP-Grammarly/issues/7

Solution:

> In `Preferences: LSP Utils Settings` one can set `"nodejs_runtime": ["local"],` to ignore system version of node.js.
