### ISSUE TITLE
Change the color for grammar/syntax error to differential from a spelling error?

### ISSUE THREAD

**Issue by dsmaynard** [sublimelsp/LSP-Grammarly#14]
Is there a way to make the squiggly lines under words different colors for spelling vs. grammar erros? Right now I have to try to guess what the mistake is first, and it would massively speed it up if these were visually different.

**Comment by rchl** [comment]
This is just a wrapper for the server at https://github.com/znck/grammarly so you should file your feature request there.

If you do then feel free to ping me.
