### ISSUE TITLE
Request for Instructions to Set Up

### ISSUE THREAD

**Issue by monomycelium** [sublimelsp/LSP-Grammarly#5]
I would love to see detailed instructions on `README.md` on how to set `LSP-Grammarly` up on macOS. After unzipping the source code from the latest release, I have no idea what to do. Should I move the directory to `/Users/mycelium/Library/Application Support/Sublime Text/Packages/User`? That is where Sublime Text would save custom plugins by default.

**Comment by chapeiro** [comment]
You do not have to install it manually. You can use [Package Control](https://packagecontrol.io/docs/usage)'s "install package" instead -- similarly to other sublime plugins (and this is a cross-OS solution).

**Comment by monomycelium** [comment]
Thank you. I think adding that line to `README.md` would be helpful.

**Comment by rchl** [comment]
Added in 07eff40d4b0a652dba1f4b0e0497ab340d807528
