### ISSUE TITLE
How Can I Know if the Plugin Is Running?

### ISSUE THREAD

**Issue by monomycelium** [sublimelsp/LSP-Grammarly#6]
I apologise for my rookie-like curiosity. How can I know if the plugin is running?

**Comment by rwols** [comment]
1. Install [LSP](https://packagecontrol.io/packages/LSP) with Package Control
2. Install [LSP-Grammarly](https://packagecontrol.io/packages/LSP-Grammarly) with Package Control
3. Open a Markdown file
4. In the lower left corner, you should see some status about Grammarly installing and then running idle

**Comment by monomycelium** [comment]
Thank you.
